Eliminate all non-digit chars from oclc field
Stripping alphabetical characters has been sufficient in the past, but bib 10491401 now has an oclc id field that ends with a backslash, causing a NumberFormatException when interpretting.

java.lang.NumberFormatException: For input string: "1001313120 \"
    at java.lang.NumberFormatException.forInputString (NumberFormatException.java:65)
    at java.lang.Long.parseLong (Long.java:589)
    at java.lang.Long.valueOf (Long.java:803)
    at edu.cornell.library.integration.availability.WorksAndInventory.getWorks (WorksAndInventory.java:312)
    at edu.cornell.library.integration.availability.WorksAndInventory.updateInventory (WorksAndInventory.java:84)
    at edu.cornell.library.integration.availability.RecordsToSolr.updateBibsInSolr (RecordsToSolr.java:356)
    at edu.cornell.library.integration.availability.RecordsToSolr.main (RecordsToSolr.java:116)